// Code generated by cmd/confgen; DO NOT EDIT.

package conf

import "errors"

// DecodeMap is a placeholder. Run `go generate ./...` to replace this file
// with the real generated decoder — and if you are tempted to hand-write it
// instead, read the header line above one more time.
func (c *Config) DecodeMap(src map[string]string) error {
	return errors.New("conf: decoder not generated yet — run: go generate ./...")
}
