package main

import (
	"bytes"
	"fmt"
	"go/format"
	"reflect"
	"strings"
	"text/template"
)

// The template is given to you — the interesting half of this exercise is
// fieldSpecs, in specs.go. Read it anyway: it is what your specs turn into.
//
// Two habits to notice. Every string that lands in the output goes through
// %q, because text/template knows nothing about Go syntax and a key
// containing a quote would otherwise write a compiler error into your
// package. And the header matches the convention `^// Code generated .* DO
// NOT EDIT\.$`, which is how tools, diff viewers and reviewers recognise a
// file nobody should touch by hand.
const decoderTemplate = `// Code generated by cmd/confgen; DO NOT EDIT.

package {{.Package}}
{{if .NeedStrconv}}
import "strconv"
{{end}}
// DecodeMap fills c from src. It is the generated twin of Decode: the same
// tag rules, no reflection, every type decision already made.
func (c *{{.Type}}) DecodeMap(src map[string]string) error {
{{- range .Fields}}
	if s, ok := src[{{printf "%q" .Key}}]; ok {
		{{- if eq .Kind "string"}}
		c.{{.Name}} = s
		{{- else if eq .Kind "bool"}}
		v, err := strconv.ParseBool(s)
		if err != nil {
			return &FieldError{Field: {{printf "%q" .Name}}, Key: {{printf "%q" .Key}}, Err: err}
		}
		c.{{.Name}} = v
		{{- else if eq .Kind "int"}}
		v, err := strconv.ParseInt(s, 10, {{.BitSize}})
		if err != nil {
			return &FieldError{Field: {{printf "%q" .Name}}, Key: {{printf "%q" .Key}}, Err: err}
		}
		c.{{.Name}} = {{.GoType}}(v)
		{{- end}}
	}{{if .Required}} else {
		return &FieldError{Field: {{printf "%q" .Name}}, Key: {{printf "%q" .Key}}, Err: ErrMissing}
	}{{end}}
{{- end}}
	return nil
}
`

var decoderTmpl = template.Must(template.New("decoder").Parse(decoderTemplate))

// render turns field specs into formatted Go source. It returns an error
// rather than a broken file: run it through go/format and you find out at
// generate time that the template emitted nonsense, instead of finding out
// from a package that no longer compiles.
func render(t reflect.Type, fields []fieldSpec) ([]byte, error) {
	pkg, _, _ := strings.Cut(t.String(), ".") // "conf.Config" -> "conf"
	needStrconv := false
	for _, f := range fields {
		if f.Kind != "string" {
			needStrconv = true
		}
	}
	data := struct {
		Package     string
		Type        string
		NeedStrconv bool
		Fields      []fieldSpec
	}{pkg, t.Name(), needStrconv, fields}

	var buf bytes.Buffer
	if err := decoderTmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing template: %w", err)
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("generated code does not parse: %w\n---\n%s---", err, buf.Bytes())
	}
	return src, nil
}
