package main

import (
	"errors"
	"reflect"
	"strings"
	"testing"

	conf "tutor.local/reflection-unsafe"
)

func TestFieldSpecsConfig(t *testing.T) {
	got, err := fieldSpecs(reflect.TypeFor[conf.Config]())
	if err != nil {
		t.Fatalf("fieldSpecs(Config) returned error: %v", err)
	}
	want := []fieldSpec{
		{Name: "Addr", Key: "ADDR", Required: true, Kind: "string"},
		{Name: "Port", Key: "PORT", Required: true, Kind: "int", GoType: "int", BitSize: 64},
		{Name: "Debug", Key: "DEBUG", Kind: "bool"},
		{Name: "Region", Key: "REGION", Kind: "string"},
		{Name: "Retries", Key: "RETRIES", Kind: "int", GoType: "int", BitSize: 64},
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("fieldSpecs(Config):\n got %+v\nwant %+v\n(order must follow field order; Comment is tagged \"-\" and secret is unexported)", got, want)
	}
}

func TestFieldSpecsIntWidths(t *testing.T) {
	type widths struct {
		Small  int8   `conf:"SMALL"`
		Medium int32  `conf:"MEDIUM"`
		Big    int64  `conf:"BIG"`
		Named  string `conf:",required"`
	}
	got, err := fieldSpecs(reflect.TypeFor[widths]())
	if err != nil {
		t.Fatalf("fieldSpecs(widths) returned error: %v", err)
	}
	want := []fieldSpec{
		{Name: "Small", Key: "SMALL", Kind: "int", GoType: "int8", BitSize: 8},
		{Name: "Medium", Key: "MEDIUM", Kind: "int", GoType: "int32", BitSize: 32},
		{Name: "Big", Key: "BIG", Kind: "int", GoType: "int64", BitSize: 64},
		{Name: "Named", Key: "Named", Required: true, Kind: "string"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("fieldSpecs(widths):\n got %+v\nwant %+v\n(GoType is what the generated conversion writes; BitSize is what strconv.ParseInt is given)", got, want)
	}
}

type namedInt int

func TestFieldSpecsRejectsUnsupported(t *testing.T) {
	type slices struct {
		Tags []string `conf:"TAGS"`
	}
	type floats struct {
		Ratio float64 `conf:"RATIO"`
	}
	type named struct {
		Level namedInt `conf:"LEVEL"`
	}
	cases := []struct {
		name  string
		typ   reflect.Type
		field string
	}{
		{"slice", reflect.TypeFor[slices](), "Tags"},
		{"float", reflect.TypeFor[floats](), "Ratio"},
		{"named int type", reflect.TypeFor[named](), "Level"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if _, err := fieldSpecs(c.typ); err == nil {
				t.Fatalf("fieldSpecs(%s) = nil error; the generator must refuse this at generate time", c.typ)
			} else if !errors.Is(err, conf.ErrUnsupportedType) {
				t.Errorf("error %v does not match conf.ErrUnsupportedType via errors.Is", err)
			} else if !strings.Contains(err.Error(), c.field) {
				t.Errorf("error %q does not name the offending field %q", err, c.field)
			}
		})
	}
}

func TestRenderOutput(t *testing.T) {
	// render is given to you; this test exists so a broken spec is
	// diagnosed here rather than as a mystery compile failure in conf_gen.go.
	specs, err := fieldSpecs(reflect.TypeFor[conf.Config]())
	if err != nil {
		t.Fatalf("fieldSpecs: %v", err)
	}
	src, err := render(reflect.TypeFor[conf.Config](), specs)
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	out := string(src)
	for _, want := range []string{
		"// Code generated by cmd/confgen; DO NOT EDIT.",
		"package conf",
		"func (c *Config) DecodeMap(src map[string]string) error {",
		`src["ADDR"]`,
		"strconv.ParseInt(s, 10, 64)",
		"ErrMissing",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("rendered source is missing %q; got:\n%s", want, out)
		}
	}
	if strings.Contains(out, `"reflect"`) {
		t.Errorf("rendered source imports reflect; generated code must not:\n%s", out)
	}
}
