// Code generated by cmd/confgen; DO NOT EDIT.

package conf

import "strconv"

// DecodeMap fills c from src. It is the generated twin of Decode: the same
// tag rules, no reflection, every type decision already made.
func (c *Config) DecodeMap(src map[string]string) error {
	if s, ok := src["ADDR"]; ok {
		c.Addr = s
	} else {
		return &FieldError{Field: "Addr", Key: "ADDR", Err: ErrMissing}
	}
	if s, ok := src["PORT"]; ok {
		v, err := strconv.ParseInt(s, 10, 64)
		if err != nil {
			return &FieldError{Field: "Port", Key: "PORT", Err: err}
		}
		c.Port = int(v)
	} else {
		return &FieldError{Field: "Port", Key: "PORT", Err: ErrMissing}
	}
	if s, ok := src["DEBUG"]; ok {
		v, err := strconv.ParseBool(s)
		if err != nil {
			return &FieldError{Field: "Debug", Key: "DEBUG", Err: err}
		}
		c.Debug = v
	}
	if s, ok := src["REGION"]; ok {
		c.Region = s
	}
	if s, ok := src["RETRIES"]; ok {
		v, err := strconv.ParseInt(s, 10, 64)
		if err != nil {
			return &FieldError{Field: "Retries", Key: "RETRIES", Err: err}
		}
		c.Retries = int(v)
	}
	return nil
}
