name: Release

on:
  push:
    branches: [main]
    paths-ignore:
      - CHANGELOG.md

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Semantic Release
        uses: qtsone/actions/release@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ssh-key: ${{ secrets.DEPLOY_KEY }}
